import Head from "next/head";
import Link from "next/link";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Mohamed_Jacuzzii</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <Link href="/resume">
                  <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8">
                    Resume
                  </a>
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Mohamed Mohamed
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I a computer science student with experience in Python and 
              Java, as well as proficiency in Git and ReactJS. He has 
              completed internships in software engineering and 
              cybersecurity and has developed personal projects, including a 
              password management program and a weather notification program.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              
              <a href="https://www.linkedin.com/in/mohamed-mohamed-31bb941b2/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Moh2520/Personal_projects">
                <AiFillGithub />
                <a href="https://stackoverflow.com/questions/4855168/what-is-href-and-why-is-it-used">
                <AiFillYoutube />
                </a>
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Work Experience</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I started working part-time jobs when I was just 15 years old, 
            which gave me a taste of the real world and an appreciation for 
            hard work. In high school, I discovered a passion for coding and 
            started experimenting with programs using Scratch. This initial 
            experience sparked my curiosity and set me on the path to becoming 
            a developer. Since then, I have continued to build my skills and 
            knowledge through various projects and experiences, and I am 
            excited to see where this journey will take me.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
